Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template to deploy system to process CloudFront realtime logs and upload as custom CloudWatch metrics
Parameters:
  KinesisShardCount:
    Description: Sets the shard count for data stream. To calculate this, add 1 Kinesis shard per 1000 requests that your CloudFront distribution receives in a second.
    Type: Number
    Default: 5
    MinValue: 1
    ConstraintDescription: KinesisShardCount must be an integer

  CloudFrontDistributionDomainName:
    Description: The domain name of the CloudFront distribution for which to process real-time logs. This should be similar to "dlhpsvkl3h8ev.cloudfront.net"
    Type: String
    AllowedPattern: ".*\\.cloudfront\\.net$"
    ConstraintDescription: CloudFrontDistributionDomainName must end in ".cloudfront.net"

Resources:
#################################################################
# RECORD_PROCESSOR Lambda, IAM Role
#################################################################
  RecordProcessorLambda:
    Type: AWS::Serverless::Function
    Properties:
      Description: Takes metrics from Kinesis data stream
      Runtime: python3.8
      CodeUri: ../src/record_processor/
      Handler: lambda_function.lambda_handler
      MemorySize: 256
      Timeout: 60
      Role: !GetAtt 'RecordProcessorLambdaExecutionIamRole.Arn'
      Environment:
          Variables:
              LOGGING_LEVEL: INFO
      Events:
        CloudfrontRealtimeLoggingStream:
          Type: Kinesis
          Properties:
            BatchSize: 10000
            Enabled: TRUE
            MaximumBatchingWindowInSeconds: 60
            MaximumRecordAgeInSeconds: -1
            MaximumRetryAttempts: 3
            ParallelizationFactor: 1
            StartingPosition: TRIM_HORIZON
            Stream: !GetAtt 'CloudfrontRealtimeLoggingStream.Arn'
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 3600

  RecordProcessorLambdaExecutionIamRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Created for record_processor Lambda
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaKinesisExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: CloudWatchMetricsPermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                Resource: "*"

#################################################################
# Kinesis Data Stream
#################################################################
  CloudfrontRealtimeLoggingStream:
    Type: AWS::Kinesis::Stream
    Properties:
      RetentionPeriodHours: 24
      ShardCount: !Ref 'KinesisShardCount'

#################################################################
# Outputs
#################################################################
Outputs:
  KinesisDataStreamArn:
    Description: ARN of the Kinesis Data Stream
    Value: !GetAtt 'CloudfrontRealtimeLoggingStream.Arn'

  RecordProcessorLambdaArn:
    Description: ARN of the RecordProcessor Lambda
    Value: !GetAtt 'RecordProcessorLambda.Arn'
